org: broccolirob
app: name-validator
service: name-validator

frameworkVersion: '3'

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x

functions:
  validate:
    handler: server/validate.handler
    events:
      - httpApi: 'POST /validate'
