org: broccolirob
app: name-validator
service: name-validator

frameworkVersion: '3'

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

functions:
  validate:
    handler: server/validate.handler
    events:
      - http:
          path: validate
          method: get
